import { field, group } from "@nuxthq/studio/theme";

export default defineNuxtSchema({
  appConfig: {
    directory: group({}),
    ui: group({
      title: "UI",
      description: "UI Customization.",
      icon: "i-mdi-palette-outline",
      fields: {
        icons: group({
          title: "Icons",
          description: "Manage icons used in UI Pro.",
          icon: "i-mdi-application-settings-outline",
          fields: {
            dark: field({
              type: "icon",
              title: "Dark mode",
              description: "Icon of color mode button for dark mode.",
              icon: "i-mdi-moon-waning-crescent",
              default: "i-heroicons-moon-20-solid",
            }),
            light: field({
              type: "icon",
              title: "Light mode",
              description: "Icon of color mode button for light mode.",
              icon: "i-mdi-white-balance-sunny",
              default: "i-heroicons-sun-20-solid",
            }),
            external: field({
              type: "icon",
              title: "External Link",
              description: "Icon for external link.",
              icon: "i-mdi-arrow-top-right",
              default: "i-heroicons-arrow-up-right-20-solid",
            }),
            chevron: field({
              type: "icon",
              title: "Chevron",
              description: "Icon for chevron.",
              icon: "i-mdi-chevron-down",
              default: "i-heroicons-chevron-down-20-solid",
            }),
          },
        }),
        primary: field({
          type: "string",
          title: "Primary",
          description: "Primary color of your UI.",
          icon: "i-mdi-palette-outline",
          default: "green",
          required: [
            "sky",
            "mint",
            "rose",
            "amber",
            "violet",
            "emerald",
            "fuchsia",
            "indigo",
            "lime",
            "orange",
            "pink",
            "purple",
            "red",
            "teal",
            "yellow",
            "green",
            "blue",
            "cyan",
            "gray",
            "white",
            "black",
          ],
        }),
        gray: field({
          type: "string",
          title: "Gray",
          description: "Gray color of your UI.",
          icon: "i-mdi-palette-outline",
          default: "slate",
          required: ["slate", "cool", "zinc", "neutral", "stone"],
        }),
      },
    }),
    seo: group({
      title: "SEO",
      description: "SEO configuration.",
      icon: "i-ph-app-window",
      fields: {
        siteName: field({
          type: "string",
          title: "Site Name",
          description:
            "Name used in ogSiteName and used as second part of your page title (My page title - Nuxt UI Pro).",
          icon: "i-mdi-web",
          default: [],
        }),
      },
    }),
    header: group({
      title: "Header",
      description: "Header configuration.",
      icon: "i-mdi-page-layout-header",
      fields: {
        logo: group({
          title: "Logo",
          description: "Header logo configuration.",
          icon: "i-mdi-image-filter-center-focus-strong-outline",
          fields: {
            light: field({
              type: "media",
              title: "Light Mode Logo",
              description: "Pick an image from your gallery.",
              icon: "i-mdi-white-balance-sunny",
              default: "",
            }),
            dark: field({
              type: "media",
              title: "Dark Mode Logo",
              description: "Pick an image from your gallery.",
              icon: "i-mdi-moon-waning-crescent",
              default: "",
            }),
            alt: field({
              type: "string",
              title: "Alt",
              description: "Alt to display for accessibility.",
              icon: "i-mdi-alphabet-latin",
              default: "",
            }),
          },
        }),
        colorMode: field({
          type: "boolean",
          title: "Color Mode",
          description: "Hide or display the color mode button in your header.",
          icon: "i-mdi-moon-waning-crescent",
          default: true,
        }),
        links: field({
          type: "array",
          title: "Links",
          description: "Array of link object displayed in header.",
          icon: "i-mdi-link-variant",
          default: [],
        }),
      },
    }),
    footer: group({
      title: "Footer",
      description: "Footer configuration.",
      icon: "i-mdi-page-layout-footer",
      fields: {
        credits: field({
          type: "string",
          title: "Footer credits section",
          description: "Text to display as credits in the footer.",
          icon: "i-mdi-circle-edit-outline",
          default: "",
        }),
        colorMode: field({
          type: "boolean",
          title: "Color Mode",
          description: "Hide or display the color mode button in the footer.",
          icon: "i-mdi-moon-waning-crescent",
          default: false,
        }),
        links: field({
          type: "array",
          title: "Links",
          description: "Array of link object displayed in footer.",
          icon: "i-mdi-link-variant",
          default: [],
        }),
      },
    }),
  },
});
